### ISSUE TITLE
how do we generate a man page?

### ISSUE THREAD

**Issue by jnweiger** [jnweiger/pdfcompare#11]
We have man/pdfcompare.xml
@tomschr What is the process to generate html, man, or pdf output formats

**Comment by tomschr** [comment]
@jnweiger Hi Jürgen! :wave: 

The easiest way is to apply the standard DocBook XSL stylesheets to your XML file. The following lists describes the easiest steps (all executed in the `man` directory):

* **Definition**:

    ```shell
DB="/usr/share/xml/docbook/stylesheet/nwalsh/current/"
```

* **Creating Manpages**:

    ```shell
xsltproc $DB/manpages/docbook.xsl pdfcompare.xml
```

* **Creating HTML**:

    ```shell
xsltproc --output pdfcompare.html $DB/xhtml/docbook.xsl pdfcompare.xml
```

* **Creating PDF**:

    ```shell
xsltproc --output pdfcompare.fo $DB/fo/docbook.xsl pdfcompare.xml
fop pdfcompare.fo pdfcompare.pdf && rm pdfcompare.fo
```

Of course, you can do much more, but you know that. :smile:

**Comment by jnweiger** [comment]
I am a github markdown user, with sphinx and pandoc these days -- forgot most of docbook :cry:

**Comment by tomschr** [comment]
Actually, to be precise and make it a little bit more platform and distribution neutral, you should replace the first step (definition) with this command:

```shell
DB=$(xmlcatalog /etc/xml/catalog http://docbook.sourceforge.net/release/xsl/current)
```

Of course, this does only work if you have working XML catalogs and the above URI resolves correctly.

**Comment by jnweiger** [comment]
<pre>xmlcatalog /etc/xml/catalog http://docbook.sourceforge.net/release/xsl/current</pre>

> No entry for SYSTEM http://docbook.sourceforge.net/release/xsl/current
> No entry for URI http://docbook.sourceforge.net/release/xsl/current

Attached the contents of /etc/xml/catalog on Ubuntu 14.04
[cat.zip](https://github.com/jnweiger/pdfcompare/files/224651/cat.zip)

**Comment by tomschr** [comment]
@jnweiger Yes, this can happen if the system doesn't have good catalog support. :cry:

The `catalog` file in the above ZIP file contains this line:

```xml
<delegateSystem systemIdStartString="http://docbook.sourceforge.net/release/xsl/" catalog="file:///etc/xml/docbook-xsl.xml"/>
```

Actually, this would delegate the URI to the `/etc/xml/docbook-xsl.xml` file. I guess, the entry is missing or they don't have the "current" part (which is only a link to the latest version).

Unfortunately, I can't look into this, I don't have an Ubuntu system ATM.
