### ISSUE TITLE
Import __future__

### ISSUE THREAD

**Issue by tomschr** [jnweiger/pdfcompare#5]
Not sure if this helps, but importing \_\_future__ can be useful, especially if you want to omit casting with float() as seen in https://github.com/jnweiger/pdfcompare/blob/master/pdf_highlight.py#L235

    from __future__ import division

Here is an example:

    # without importing divison from __future__:
    >>> 1/2
    0
    >>> float(1)/2
    0.5
    >>> from __future__ import division
    >>> 1/2
    0.5

For more information, see http://www.python.org/dev/peps/pep-0238/

**Comment by jnweiger** [comment]
Some float() casts remain, where FloatObjects need to perform math.
Some int() casts added, where an integer division result is expected.
